// action types
export const TOGGLE_FEED_VIEW = 'TOGGLE_FEED_VIEW'
export const CANCEL_SELECTING = 'CANCEL_SELECTING'
export const SELECT_NOTE = 'SELECT_NOTE'
export const DESELECT_NOTE = 'DESELECT_NOTE'
export const DELETE_SELECTED_NOTES = 'DELETE_SELECTED_NOTES'
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'
export const CANCEL_DELETION = ' CANCEL_DELETION'
export const START_REFRESH = 'START_REFRESH'
export const PIN_NOTES = 'PIN_NOTES'
export const UNPIN_NOTES = 'UNPIN_NOTES'


// deletionId types
export const DELETION_DELETE = 'DELETION_DELETE'


// notification types
export const NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS'
export const NOTIFICATION_INFO = 'NOTIFICATION_INFO'
export const NOTIFICATION_WARNING = 'NOTIFICATION_WARNING'
export const NOTIFICATION_DANGER = 'NOTIFICATION_DANGER'


// refresh statuses
export const REFRESH_IN_PROGRESS = 'REFRESH_IN_PROGRESS'
export const REFRESH_ERROR = 'REFRESH_ERROR'
export const REFRESH_DONE = 'REFRESH_DONE'
