/**
* action types
*/
export const SET_PAGE = 'SET_PAGE';
export const TOGGLE_FEED_VIEW = 'TOGGLE_FEED_VIEW';
export const CLEAR_SELECTION = 'CLEAR_SELECTION';
export const TOGGLE_SELECT_NOTE = 'TOGGLE_SELECT_NOTE';
export const SELECT_NOTE = 'SELECT_NOTE';
export const DESELECT_NOTE = 'DESELECT_NOTE';
export const TAG_NOTE = 'TAG_NOTE';
export const MOVE_NOTES_TO_TRASH = 'MOVE_NOTES_TO_TRASH';
export const RESTORE_NOTES_FROM_TRASH = ' RESTORE_NOTES_FROM_TRASH';
export const CLEAR_TRASH = 'CLEAR_TRASH';
export const EMPTY_TRASH = 'EMPTY_TRASH';
export const DELETE_NOTES = 'DELETE_NOTES';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
export const START_REFRESH = 'START_REFRESH';
export const PIN_NOTES = 'PIN_NOTES';
export const UNPIN_NOTES = 'UNPIN_NOTES';
export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';
export const ENTER_SEARCH_MODE = 'ENTER_SEARCH_MODE';
export const EXIT_SEARCH_MODE = 'EXIT_SEARCH_MODE';
export const TOGGLE_MAIN_MENU = 'TOGGLE_MAIN_MENU';
export const EDIT_NOTE = 'EDIT_NOTE';
export const START_EDITING_NOTE = 'START_EDITING_NOTE';
export const END_EDITING_NOTE = 'END_EDITING_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const SAVE_EDITED_NOTE = 'SAVE_EDITED_NOTE';
export const SHOW_TAGS_MODAL = 'SHOW_TAGS_MODAL';
export const HIDE_TAGS_MODAL = 'HIDE_TAGS_MODAL';
export const CREATE_TAG = 'CREATE_TAG';
export const DELETE_TAG = 'DELETE_TAG';
export const SAVE_EDITED_TAG = 'SAVE_EDITED_TAG';


/**
* deletionId types
*/
export const DELETION_DELETE = 'DELETION_DELETE';


/**
* notification types
*/
export const NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS';
export const NOTIFICATION_INFO = 'NOTIFICATION_INFO';
export const NOTIFICATION_WARNING = 'NOTIFICATION_WARNING';
export const NOTIFICATION_DANGER = 'NOTIFICATION_DANGER';


/**
* pages
*/
export const PAGE_HOME = 'PAGE_HOME';
export const PAGE_TRASH = 'PAGE_TRASH';


/**
* refresh statuses
*/
export const REFRESH_IN_PROGRESS = 'REFRESH_IN_PROGRESS';
export const REFRESH_ERROR = 'REFRESH_ERROR';
export const REFRESH_DONE = 'REFRESH_DONE';
